version: '3'

services:
  ignite:
    image: apacheignite/ignite:2.6.0
    container_name: ignite-node
    volumes:
      - ./ignite:/opt/test
    environment:
      - CONFIG_URI=file:///opt/test/test.xml
      - USER_LIBS=/opt/test/assembly
    command: sh /opt/test/start-ignite.sh
  app:
    image: openjdk:8
    container_name: ignite_client
    volumes:
      - ./ignite-test-worker/target:/opt/assembly
      - ./ignite:/opt/test
    command: java -jar /opt/assembly/ignite-test-worker-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/test/client.xml test 100000
